name: Run Pytest

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          os: ${{matrix.os}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          os: ${{matrix.os}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PAModelpy  # If you have a requirements.txt file

      - name: Run Pytest
        run: pytest
        with:
          os: ${{matrix.os}}
