name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      job: ${{ needs.test.outputs.job }}

      steps:
        - name: Trigger common job
          id: test
          uses: ./.github/workflows/common.yml
